version: '3'
services:

  epic-a:
    image: luminoleon/epicgames-claimer:latest
    container_name: epic-a
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - AUTO_UPDATE=false
      - EMAIL=邮箱
      - PASSWORD=密码
    volumes:
      - $PWD/User_Data:/User_Data
  # epic-b:
    # image: luminoleon/epicgames-claimer:latest
    # container_name: epic-b
    # restart: unless-stopped
    # environment:
      # - TZ=Asia/Shanghai
      # - AUTO_UPDATE=false
      # - EMAIL=另一个邮箱
      # - PASSWORD=另一个密码
    # volumes:
      # - $PWD/User_Data:/User_Data